### ISSUE TITLE
1.x deprecations

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#105]
- [ ] 'token' field from returned json of /token endpoint, [see](https://github.com/apigee/apigee-remote-service-cli/issues/80)
- [ ] token bindings 'add', 'remove', and 'verify' commands

**Comment by rockspore** [comment]
If we are switching to Envoy V3 which breaks 1.5+ from 1.4.x. Should we consider including these as well?

**Comment by theganyo** [comment]
Yes. Let's do it.
