### ISSUE TITLE
token service does not support "--legacy" or "--opdk" flags

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-cli#12]
Those two flags are not checked in token level. Yet the error message still says:
```
apigee-remote-service-cli token rotate-cert -o hi -e -test   
Error: --runtime is required for hybrid or opdk (or --organization and --environment with --legacy)
```
which seems misleading to me.

**Comment by theganyo** [comment]
Are they not checked in resolve?

**Comment by rockspore** [comment]
For this specific case, I believe `isGCPManaged` flag is turned on because neither legacy or opdk is set.

**Comment by theganyo** [comment]
Sounds like we need to add those flags then.
