### ISSUE TITLE
Error re-running "cli provision"

### ISSUE THREAD

**Issue by gbrail** [apigee/apigee-remote-service-cli#121]
If I try to run "apigee-remote-service-cli provision" more than once for the same GCP project, I get the following:

Error: creating policy secret data: POST https://apigee.googleapis.com/v1/organizations/XXX/environments/YYY/resourcefiles?name=remote-service&type=properties: 409 {409 cannot create resource organizations/XXX/environments/YYY/resourcefiles/properties/remote-service; already exists ALREADY_EXISTS}

This may have to do with the specific version of Apigee SaaS that I am using.

Deleting the resource using the API and re-running works fine.

**Comment by rockspore** [comment]
This is expected such that it does not overwrite the existing resources. To overwrite the resource, one needs to run the provision command with the rotate flag, for example, `--rotate 1`.

Such implementation is to make it "consistent" with Apigee Hybrid, where users themselves need to apply the new config.yaml to the cluster to replace the secrets/configmaps.

**Comment by theganyo** [comment]
We could add an explanatory message to this.

**Comment by rockspore** [comment]
We will change the provision logic to return a config with secrets in the existing propertysets in this case.
