### ISSUE TITLE
verifyRemoteServiceProxy() is not checking response status code

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-cli#123]
It currently lets any status code through as long as the http client does not return error on the actual request.

**Comment by theganyo** [comment]
I'm not sure what this is referring to exactly, but IIRC, some of the checks needed to allow "bad" status codes.

**Comment by rockspore** [comment]
401 from `/verifyApiKey` is and should be allowed. But that's the only status code that's being explicitly checked right now.

For example, 503 from a GET request to `/version` is being ignored.

**Comment by theganyo** [comment]
For most endpoints, it requires an internal token and/or certificate - so the requests may not yet be able to be verified. Yes, /version would an exception. Why is it getting a 503?

**Comment by rockspore** [comment]
503 was because my runtime pod was not active at the time.

Essentially, we shouldn't solely rely on the error from the go http.Client, which does not return error on non-2xx status code. See the doc: 

```
// An error is returned if caused by client policy (such as
// CheckRedirect), or failure to speak HTTP (such as a network
// connectivity problem). A non-2xx status code doesn't cause an
// error.
```

**Comment by theganyo** [comment]
Right. I understand the status code issue you're raising, I'm just saying that in many cases we can't expect a "good" response. Feel free to propose enhancements... but we should still ensure that we don't raise unnecessary or confusing warnings/errors to the user and that they don't block the generation of the configuration.

**Comment by rockspore** [comment]
Yes. I understand we can't fully verify all the proxies' functionality without valid credentials. That will be left for the integration test.

But since deploying a proxy can be asynchronous, it will be useful to ensure the endpoints are active before a config is generated and used. I will work on adding some check of the status codes.
