### ISSUE TITLE
`/products` returns products in all Apigee environments

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-cli#144]
This is achievable by configuring the callout policy. It will pave the way for supporting multi-environments.

Meanwhile, as long as we utilize the Apigee environment embedded in `auth.Context`. The single-env setup will still work exactly the same way. The disadvantage that can be thought of is the adapter, in this single-env setting, will possibly receive and maintain a much bigger list of products than needed.

**Comment by rockspore** [comment]
The above disadvantage may be addressed by configuring the `/products` endpoint to take the environment as an optional param and turn on/off this filter as needed. The -golib repo needs to make corresponding change in requesting products.

This is related to https://github.com/apigee/apigee-remote-service-golib/issue/36

**Comment by theganyo** [comment]
I'll add the support to -golib in the currently open PR on golib. Will pass the env like this: `/products?env=test`. We'll just need to make sure the default for the proxy is all environments and use this query param, if present.

**Comment by rockspore** [comment]
For the record, currently the java callout does not support taking arbitrary environments. If the filter by environment is enabled, it will use the environment where the proxy is deployed. Therefore, the java callout itself needs a change.

**Comment by theganyo** [comment]
Ok, for now we can just set it to return all products and add the optimization when the java callout is updated.
