### ISSUE TITLE
divide remote-service proxy into runtime and token proxies

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#151]
Users need to be able to tweak their JWT Token endpoints without getting overridden with new internal API proxy changes during provisioning. In order to make this easier for customers, we'll divide the existing single proxy into two proxies:

### remote-service

This is the runtime API for the Envoy Adapter and should not be considered customizable. It is the proxy we install today, minus the endpoints that are being moved to the customizable proxy.

#### endpoints:
- /products
- /quotas
- /rotate
- /verifyAPIKey
- /version

This proxy will be be installed during provisioning as it is today.

### remote-token

This proxy will offer the customer a sample of token generation that is customizable without being overridden in new installs. This way, the the customer may customize their OAuth flows and change their certificate without affecting the operation of the Envoy Adapter.

#### endpoints:
- /token
- /certs

This proxy will be installed if it is not found during provisioning, but otherwise left untouched.

By default, this proxy will utilize the same certificate that is installed for the `remote-service` internal operations.

**Comment by theganyo** [comment]
Note: As written, this would break anyone using the `/remote-service/token` and `/remote-service/certs`.

@srinandan - please review this design

**Comment by rockspore** [comment]
Would it be better to call the second proxy as `remote-oauth`?
