### ISSUE TITLE
multi-tenant config cannot be referenced for provisioning

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#152]
If a user modifies their config for multi-tenancy (ie. sets env_name to "*"), that config can't be used to run provision for upgrades and instead receives an error similar to the following:

```
Error: deploying proxy remote-service: deploying proxy remote-service: POST https://apigee.googleapis.com/v1/organizations/myorg/environments/%2A/apis/remote-service/revisions/1/deployments?override=true: 400 {400 invalid deployment name "organizations/myorg/environments/*/apis/remote-service/revisions/1": "*" is an invalid Environment ID INVALID_ARGUMENT}
```

Attempting to override the env in the command is ignored. However, allowing the CLI to override may be the best way handle this case. I can't think of a reason to not do this.

**Comment by theganyo** [comment]
Note: This might apply to commands other than provision. I haven't audited that.

**Comment by rockspore** [comment]
> Note: This might apply to commands other than provision. I haven't audited that.

To confirm this: currently whatever in the config file supersedes those given through flags.
