### ISSUE TITLE
support remote-service + remote-token proxies on cgsaas and opdk

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-cli#157]
This was overlooked in #156. We don't rely on propertyset or k8s secrets for these two platforms to generate oauth tokens.

**Comment by theganyo** [comment]
The new proxies are only installed for GCP platforms. What did we miss?

**Comment by rockspore** [comment]
I can see the cgsaas test got the two proxies installed. And `token` command now exclusively goes to `/remote-token` for JWT.

Also, `templates.go` was but rebuilt.

**Comment by rockspore** [comment]
I thought the dividing the proxies should apply to all platforms from #151. And that would make it consistent across them.

**Comment by theganyo** [comment]
Ah, I [see](https://github.com/apigee/apigee-remote-service-cli/blob/master/cmd/provision/provision.go#L243). It was intended to be GCP only, but the check was missed. That said, maybe you're right and we should go ahead and change the other platforms as well.
