### ISSUE TITLE
Add the Envoy Header To Metadata Filter to the sample

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#162]
Once we implement [use metadata instead of headers for authz -> ALS](https://github.com/apigee/apigee-remote-service-envoy/issues/146), we should add the [Header To Metadata Filter](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/header_to_metadata/v2/header_to_metadata.proto) as part of the generated sample.

**Comment by rockspore** [comment]
It seems like we don't need this extra filter. Everything will already be in metadata based on the -envoy issue.

That said, we do need to modify RBAC rules and remove those additional headers in ALS in the template config.

**Comment by theganyo** [comment]
Thanks!
