### ISSUE TITLE
Remove RBAC filter in Envoy and Istio templates

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-cli#165]
There is no reason for it to exist based on discussions in #163, https://github.com/apigee/apigee-remote-service-envoy/issues/149 and https://github.com/apigee/apigee-remote-service-envoy/issues/146.

**Comment by rockspore** [comment]
Based on https://github.com/envoyproxy/envoy/pull/11820, the `ext_authz` filter will only emit dynamic metadata if the `ext_authz` server returns an OK response. While switching to metadata still brings benefit over using headers, it seems we can't get rid of the RBAC filter here...

**Comment by theganyo** [comment]
That's terrible news. :(
