### ISSUE TITLE
Istio EnvoyFilter CRs must have version guards

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#175]
Add version guards to EnvoyFilters. As in this [example](https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.10.yaml#L22), we should have a single EnvoyFilter CRD across Istio versions with appropriately guarded patch elements to enable smooth upgrades for customers as the proxy versions change in Istio.

**Comment by rockspore** [comment]
To clarify: the proxy version is the Istio version instead of Envoy version.
