### ISSUE TITLE
remove the runtime_version dependency from the /products endpoint

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-cli#178]
The runtime version related variable could either be `v140` or `1-4-0-....`. We need to modify the python callout to support either one.

**Comment by rockspore** [comment]
Instead of the change above, we will remove the runtime_version dependency of /products endpoint.

The endpoint will attempt to execute the new java callout and continue with the old java callout on error or skip the old java callout on success.

This may introduce a little bit of overhead for hybrid 1.3.x but will have no impact on 1.4.x and future versions.

**Comment by theganyo** [comment]
Maybe not instead, but in addition to... reporting the correct version is still useful for the /version endpoint, but not rely on that version for the /products callout.

**Comment by rockspore** [comment]
Good point! My actual plan is indeed "in addition to".

> Maybe not instead, but in addition to... reporting the correct version is still useful for the /version endpoint, but not rely on that version for the /products callout. (That may already be what you meant.)

Good point! My actual plan is indeed "in addition to" :-)
