### ISSUE TITLE
`/products` take boolean value from the request for the environment filter

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-cli#200]
See https://github.com/apigee/apigee-remote-service-envoy/issues/211

**Comment by rockspore** [comment]
In addition to the boolean value, it should also take the attribute name of configure the callout policy instead of hard coding a `apigee-remote-service-targets` as is right now.

**Comment by theganyo** [comment]
We need to be careful with this. It affects the product cache(s) and etags.

**Comment by rockspore** [comment]
We will keep the environment filter off in the callout policy till it becomes an issue.
