### ISSUE TITLE
Access Entity policy supports JSON

### ISSUE THREAD

**Issue by srinandan** [apigee/apigee-remote-service-cli#212]
**Describe the issue**
The `remote-service` API Proxy uses the XMLToJSON policy to convert from XML to JSON the data read from Access Entity policy.  

**Describe the solution**
The Access Entity policy supports JSON (ref: https://cloud.google.com/apigee/docs/api-platform/reference/policies/access-entity-policy#outputformat-element)

**Describe alternatives you've considered**

**Additional context**

**Comment by rockspore** [comment]
JSON output format was only introduced in Hybrid 1.4. Unless we are dropping 1.3.x support we can't switch.

**Comment by theganyo** [comment]
Hybrid 1.3 isn't even deprecated yet, I don't think we'll be able to address this issue for some time. Should we keep in icebox for future reference?

**Comment by srinandan** [comment]
Hybrid 1.3 is now deprecated (https://cloud.google.com/apigee/docs/hybrid/versions)

**Comment by theganyo** [comment]
Deprecated just means we can drop it in a year, right?

**Comment by rockspore** [comment]
> Deprecated just means we can drop it in a year, right?

Hmm, true, maybe 9 months as I heard about this last time. But still means we can't drop it immediately.

**Comment by rockspore** [comment]
I verified this is feasible and would save us 2+ policies.
