### ISSUE TITLE
apigee runtime version not evaluated correctly

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#253]
In the remote-service proxy that is deployed to Apigee as part of the Envoy Adapter setup, there is a Python callout in the 'Get API Products' endpoint that does a check for the current Apigee runtime version. The code breaks when the minor version is not a single digit, i.e. it breaks with the latest runtime version 1-10-0-apigee-1

```
get-runtime-version.py:
version = os.environ.get("APIGEE_DPCOLOR", "")

if len(version) > 0:
    dig = [c for c in version if c.isdigit()]
    flow.setVariable("runtime_version", ".".join(dig[0:3]))
else:
    flow.setVariable("runtime_version", "unknown")
```

The resulting output is 1.1.0, not 1.10.0 as would be expected.

Also, in the subsequent policy in the proxy, there is a conditional check for ("runtime_version LesserThan "1.5.0").
This also breaks if runtime_version is '1.10.0' as the string compare of '1.10.0' < '1.5.0' evaluates as true

**Comment by rockspore** [comment]
While it is a bug, I don't think the conditional check still exists.

**Comment by theganyo** [comment]
Thanks, I agree. I don't see that check in any policy we create anymore either.

**Comment by gautambaghel** [comment]
Any progress on this? I think I'm hitting this bug and I am hitting that conditional expression as well

**Comment by gautambaghel** [comment]
It's actually related to this: https://github.com/apigee/apigee-remote-service-envoy/issues/406

I had to manually go there and update the version to 1.10.0 and when I did that it was returning 0 products

**Comment by theganyo** [comment]
@gautambaghel Please take a look at PR #254.
