### ISSUE TITLE
Bindings for OPDK does not take a `--management` flag but uses the `--runtime` flag as the management url

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-cli#29]
In this way, if one uses the `--runtime` flag to pass the management url it works fine. But if a valid config.yaml is also specified in addition to it, the cli will uses the runtime inside and returns error.

**Comment by rockspore** [comment]
Is this desired?
https://github.com/apigee/apigee-remote-service-cli/blob/58d4b5995add551dc759e97f6ab056ff82acf940/shared/shared.go#L132

**Comment by theganyo** [comment]
The thought was that the runtime would be the same as the management for OPDK cases.

**Comment by rockspore** [comment]
> The thought was that the runtime would be the same as the management for OPDK cases.

We can keep that assumption. But it makes sense if user can override it through `--management`. And `--runtime` should only be an optional flag even without a config.yaml.

**Comment by theganyo** [comment]
Sounds good.
