### ISSUE TITLE
AssignMessage Response createNew true

### ISSUE THREAD

**Issue by srinandan** [apigee/apigee-remote-service-cli#33]
**Describe the issue**
AssignMessage policies which are used to send a response should set createNew="true". This will prevent request headers from being copied to the response. When request headers are copied to the response, it can interfere with http 2. The workaround was to turn off http 2 on the client (apigee-remote-service-envoy).

However, if createNew is set to true, then http 2 can be used by apigee-remote-service-envoy.

**Steps to Reproduce**
Run apigee-remote-service without setting `GODEBUG=http2client=0` you will notice errors like this:

stream error: stream ID 11; PROTOCOL_ERROR; mix of request and response pseudo headers

**Platform (include version)**
OS: 
Envoy: 
Kubernetes: 1.16
Istio: ASM 1.5.8

**Additional context**

**Comment by rockspore** [comment]
I am still getting the same error after all relevant policies are updated. Is there any other details that I could be missing? @srinandan

**Comment by rockspore** [comment]
Update: `createNew=true` does work but the `/verifyApiKey` currently has no AssignMessage policy. I will modify that endpoint to resolve this.
