### ISSUE TITLE
NG SaaS provisioning

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#39]
Evaluate and make necessary changes to `provision` for NG SaaS. This will basically be the Hybrid provision with the addition of calling the APIs to set up proper [Property Sets](https://cloud.google.com/apigee/docs/api-platform/cache/property-sets). The emitted config shouldn't have to change.

Also, we shouldn't need to ask the user to make any distinction between Hybrid and NG SaaS for provisioning. The Management URI is the same and the type of deployment is available via API: `/v1/organizations/{org}`:

```
{
  "analyticsRegion": "us-west1",
  "authorizedNetwork": "default",
  "runtimeType": "CLOUD",
  "subscriptionType": "PAID",
}
```

(where `runtimeType == CLOUD || HYBRID`)

Finally, we should be able to use the same proxy between these environments as well - although we'll need to read from different variable names. This can be done in a simple javascript to set a common var - depending on which exists.

**Comment by rockspore** [comment]
The propertyset has a length limit on the keys and values. Specifically the value cannot exceed 1024 bytes, which seems insufficient to hold the private key.

**Comment by theganyo** [comment]
@srinandan We may have an issue. ^

**Comment by rockspore** [comment]
It works by splitting the key into two parts and having them merged in the jsc callout.

**Comment by theganyo** [comment]
Sounds like a good hack, but I think we need a proper solution. This could also affect the public keys.
