### ISSUE TITLE
provision `remote-service` API Product

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#4]
provisioning should create an API Product called `remote-service` with the endpoints:

/verifyApiKey
/token

Once done, docs must be updated to ask users to always add that API Product to their apps.

**Comment by rockspore** [comment]
Doesn't this also apply to Edge Public?

**Comment by theganyo** [comment]
Sorry, yes: Not just hybrid. All platforms including OPDK. Will update.
