### ISSUE TITLE
Retiring Basic Auth

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#44]
Apigee will soon block basic auth calls for organizations that have turned on multi-factor authentication. We need to switch basic auth calls to OAuth2.

**Comment by theganyo** [comment]
I believe we should be able to do internally without affecting the user interface.

**Comment by rockspore** [comment]
One fairly easy way, if not elegant, is let the `EdgeClient` get an OAuth token upon construction if the management base is `https://api.enterprise.apigee.com`. For what the cli does, token refreshing shouldn't be needed.

**Comment by theganyo** [comment]
I agree. Also, generating the token for each time the CLI is run should be fine and will avoid having to maintain local state.
