### ISSUE TITLE
cli commands with no params should just print usage, not error

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#46]
Example:
```
$ apigee-remote-service-cli bindings verify
Error: --token is required for hybrid
Usage:
  apigee-remote-service-cli bindings verify [product name (optional)] [flags]
```

Proper behavior would be no error, just the usage. This happens for many, if not most, commands.

**Comment by rockspore** [comment]
Based on how cobra works, those deepest commands with Run() or RunE() defined will be executed regardless of how many flags are set (only args can be checked by us), and the usage string will only be printed if err occurs from the execution. So while we can assign some "dummy" error when no flag is set, I am not sure if this is really what we want.

**Comment by theganyo** [comment]
Hmm. I thought there was a way to make it print usage.

**Comment by rockspore** [comment]
> Hmm. I thought there was a way to make it print usage.

The function to get the usage string is available. I am just not sure if there is a way to tell it to skip the execution.
