### ISSUE TITLE
Token support for cases such as SAML users on CG SaaS

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-cli#64]
Currently, `--token/-t` is being described as Hybrid only. It should officially support cases such as SAML users on CG SaaS.

Background: Since the v1.1.0 release where the MFA for CG SaaS is being supported, the CLI will attempt to fetch an OAuth token based on the username/password (and a MFA token if needed) when `--legacy` is specified. This will prevent the user passed token from being applied.

**Comment by theganyo** [comment]
Related: https://docs.apigee.com/api-platform/system-administration/enabling-saml-authentication-edge

**Comment by rockspore** [comment]
> Related: https://docs.apigee.com/api-platform/system-administration/enabling-saml-authentication-edge

Thanks! Based on the `Get the machine user's OAuth2 tokens` section, v1.0.0 definitely should work. And we just need to prevent the given token from being overwritten by MFA OAuth attempt, which will be a fairly simple fix.
