### ISSUE TITLE
Headless service exposing the adapter?

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-cli#73]
Should we change the template to expose the adapter as a headless service? It won't matter if the sample config is just used for testing so I am not sure.

Also `clusterIP` in the service spec is an immutable field.

**Comment by rockspore** [comment]
Some related docs: https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

**Comment by theganyo** [comment]
Are there any potential negative ramifications of doing so, either in stand-alone K8s or within Istio?

**Comment by rockspore** [comment]
I have confirmed that in the case where Envoy sidecars are managed by Istio, the ext_authz server will be load balanced with a headless service.

But since in general there should be more Envoy proxies than the adapters, besides the server terminates TLS connection longer than 10 minutes, let's not add it to the sample config (immutability of `clusterIP` could be annoying). I will write a short  wiki page describing this and we may add it to the official doc if needed.

**Comment by rockspore** [comment]
https://github.com/apigee/apigee-remote-service-cli/wiki/Load-balancing-of-the-adapter-service-in-Kubernetes-clusters

**Comment by theganyo** [comment]
Sounds good. Thanks!
