### ISSUE TITLE
Apigee OAuth response does not conform to OAuth 2 spec

### ISSUE THREAD

**Issue by srinandan** [apigee/apigee-remote-service-cli#80]
Issues filed on Github are not subject to service level agreements (SLAs) and responses should be
assumed to be on an ad-hoc volunteer basis. The [Apigee community board](https://community.apigee.com/) 
is recommended as for community support and is regularly checked by Apigee experts.

Apigee customers should use [formal support channels](https://cloud.google.com/apigee/support).

---
**Describe the issue**
The OAuth token response does not conform to the RFC [here](https://tools.ietf.org/html/rfc6749)

**Additional context**
I have made the changes here: https://github.com/srinandan/apigee-remote-service-cli/blob/master/proxies/remote-proxy-gcp/apiproxy/resources/jsc/set-response.js

**Comment by rockspore** [comment]
What does the flow variable `scp` mean? Can I find its documentation somewhere?

**Comment by srinandan** [comment]
It is coming from here: https://github.com/apigee/apigee-remote-service-cli/blob/master/proxies/remote-proxy-gcp/apiproxy/policies/Extract-OAuth-Params.xml#L32

**Comment by rockspore** [comment]
> It is coming from here: https://github.com/apigee/apigee-remote-service-cli/blob/master/proxies/remote-proxy-gcp/apiproxy/policies/Extract-OAuth-Params.xml#L32

Sorry I missed it. Thanks!

**Comment by theganyo** [comment]
For release notes: `token` field is deprecated, replaced by `access_token` per OAuth spec https://tools.ietf.org/html/rfc6749#section-5.1
