### ISSUE TITLE
`samples create` console output

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-cli#92]
A couple of issues from the output below:

1. `supersededGenerating` - missing newline
2. `fluentd endpoint if present` - it has the config to look at, why say `if`?
3. `config files successfully generated.` - Capitalize as a sentence or remove the period.

```
$apigee-remote-service-cli samples create -c xxx --out samples -t istio-1.7
service account credentials are found in config, the fluentd endpoint if present will be supersededGenerating istio-1.7 configuration files...
  generating apigee-envoy-adapter.yaml...
  generating envoyfilter-sidecar.yaml...
  generating httpbin.yaml...
  generating request-authentication.yaml...
config files successfully generated.
Please enable istio sidecar injection on the default namespace before running kubectl apply on the directory with config files.

**Comment by rockspore** [comment]
Regarding the second point, based on how `provision` is working till the merge of #93, it is possible to have both fluentd endpoint and service account credentials in the `config.yaml`. Superseding the fluentd endpoint merely means the mtls volume will not be included in the adapter deployment spec.

We can remove this sentence now that fluentd is discouraged. But it seems the behavior doesn't need to change.

**Comment by theganyo** [comment]
Or maybe change the verbiage to be more clear and only print when necessary?

**Comment by rockspore** [comment]
> Or maybe change the verbiage to be more clear and only print when necessary?

Sounds good.
